### PR TITLE
Update to do nested structures

### PR DESCRIPTION
**Pull request by sapanshah**
Reviewers: @ericjperry @KrisSiegel

### CODE REVIEW

**Comment by KrisSiegel** [comment]
Seems fine to me. We might want to include a default bakula_config.json in the top level directory though otherwise you can't just clone this repo and run it.

**Comment by ericjperry** [comment]
Had a conversation with @sapanshah offline because there are a couple issue with this. He's working them now.

**Comment by ericjperry** [comment]
:+1:

**Comment by ericjperry** [comment]
@KrisSiegel hurry up and thumbs up so I can put in my dependent PR. :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb: :bomb:

**Comment by KrisSiegel** [comment]
Soup and I were talking about this offline before my kids interrupted. I'll :+1: for now but I think we may want to change a couple of things up. It's weird that we'd have to run unflatten since that is its original state and we still need a default configuration.

**Pull request merged**
